### PR TITLE
fixed create-delete-in-drawer-plugin.cy.js

### PR DESCRIPTION
**Pull request by ghost**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #0001

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by FangSen9000** [comment]
Well, I will keep an eye on your PR, immediately and continuously merge any branches

**Comment by FangSen9000** [comment]
image

Will the changes in the blue circle below affect you

**Comment by ghost** [comment]
Hi Sen,

I can see now that the CI had concluded. But more problems arises, Do you
have any ideas on how we might approach this?

**Comment by FangSen9000** [comment]
>
image

The file you modified is in the plugin file, and its result has just come out.
Only these three deserve attention. The other rest will pass if you refresh more：

I suggest that you complete 1 and 3 first. 1 is what you are completing and 3 is 100% problematic.
2 has a 10% pass rate. I spent three days to find that no matter how I changed it, it did not affect his low pass rate

**Comment by ghost** [comment]
Hi Sen,

Is there a way we can get screenshots from github actions?

I don't know what happened there [:confused]

**Comment by FangSen9000** [comment]
> Hi Sen, Is there a way we can get screenshots from github actions? I don't know what happened there [:confused]

@butterfly1924   I've been searching. This seems to work！
https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-slack
and 
https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-workchat

This looks like an interesting thing. It's a GitHub action, which is used to download screenshots and pictures. I think if we have this, it will help developers a lot in the future. 

There are really many strange things, such as if there is a problem with the logic of a test case, why does it occur when it is changed. It seems that there are non objective factors, such as the pass rate after the merger.

You can have a look **Plugin-schema.cy.js** tomorrow. It is 100% defective. It can be debugged locally. Call me at any time. I will let it run in the workflow.

**Comment by FangSen9000** [comment]
> > Hi Sen, Is there a way we can get screenshots from github actions? I don't know what happened there [:confused]
>

I will open a PR tomorrow to try this workflow. I hope it can run well. This is what we urgently need.
https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-slack

cc @bzp2010 @guoqqqi @Baoyuantop

**Comment by ghost** [comment]
Great

**Comment by FangSen9000** [comment]
@bzp2010      
https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-slack

I tried to complete it, but it involved some permissions and was finally prohibited from running in the workflow. I think the addition of this function is of great significance:

1. It can greatly help developers find some online errors.
2. It can enable other developers to watch PR's cypress and help each other find errors faster. Not just from a text report. Even an infinite number of testers can see a person's PR operation, instead of having to reproduce or try locally (and only one person can see it)
3. In the future, we can help judge whether the error of a PR is related to the new function through the video in the slack workspace, so as to judge more accurately whether to merge. Increase the efficiency of update iteration.
4. If we often watch the operation of Ci and improve it, it is likely to achieve 100% online accuracy in the end. I'm afraid many tests are caused by online particularity.

@bzp2010 This PR is very cost-effective. I think you can try it if you have the authority. It took me only 3 hours to complete it. It is very easy, but it is a very meaningful thing for the future development of dashboard. Maybe you can try it in your spare time. I opened an issue: https://github.com/apache/apisix-dashboard/issues/2616
 
I will pay attention to your work. If you want to have a try and have any questions, please ask me.

cc @butterfly1924

**Comment by FangSen9000** [comment]
@butterfly1924 It seems that the function of online viewing test needs to wait, because it involves some permissions, such as slack adding robots, warehouse adding workflow, and warehouse communication settings.
Take a look at the 100% failed plugin-schema.cy.js first. As long as this is solved, all developers can still pass the test cases. As long as they refresh enough... This schema can also be solved locally.

**Comment by FangSen9000** [comment]
@butterfly1924 
Only two test cases failed this time, one related to route (random generation) and the other to plugin (0% of the test cases that no one can pass)

image


image

As you can see, the routing error this time is different from yesterday, so it is very random. You don't have to worry about e2e/route. There is no need to try to fix the use case of route.

image

I remember I said that when you worked, his pass rate was low, but it was not 0. Look, I passed this time. Perhaps our change has indeed improved the pass rate of create-delete-in-drawer-plugin.cy.js ，congratulations.

If you can't watch the video running online for the time being, take a look at **plugin-schema.cy.js** first.

**Comment by FangSen9000** [comment]
@butterfly1924 I have also looked plugin-schema.cy.js before. The error of its case11 is that there is no name input, resulting in an illegal prompt. 

501979b400e929e0b2598d6c99a5298

In fact, he should have given an illegal prompt, but he judged that it should not appear, so he made a mistake. Here is a judgment: shouldValid, which is located in e2e/commands.js. You can have a look。

image

Then, after reaching case12, Dashboard unexpectedly jumps out of the page and returns to the login page, because it will log in only once before each assertion. The unexpected situation of jumping out of the page was not considered, so the detection could only find non-existent plug-ins on the login page, so an error occurred. You can have a look.

I hope my information can help you. I will merge any PR of you at any time.

**Comment by FangSen9000** [comment]
@butterfly1924 Dude, don't forget the dashboard issue, two more PR's recently failed to merge due to test cases. I also want to solve this plugin-schema.cy.js, but I can't find the reason. I feel that the logic is ok. 🥲

**Comment by ghost** [comment]
Hi wirth,
This plugin is no longer enabled here in this context. I am not sure if it
is affected or so. What I am sure is that the CI will no longer fail here.

Regards,
Feng Han

**Comment by FangSen9000** [comment]
Two weeks ago, all the use cases were fixed and the Ci was back to normal. Part of what is drawer.js is the lack of {forcus:true}



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 11, 2022 14:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [FangSen9000/apisix-dashboard] fixedcreate-delete-in-drawer-plugin.cy.js (PR #8)

**Pull request merged**
